packages:
  - 'packages/**'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.2.5
overrides:
  vite: 'catalog:'
shamefullyHoist: true
minimumReleaseAgeExclude:
  - '@soybeanjs/cli@1.7.3 || 1.7.4'
