// Auto-generated by ubean - do not edit manually
/* eslint-disable */
/* @ts-nocheck */

export interface paths {
  '/api/cookies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cookie validation test
     * @description Test endpoint for cookie validation.
     */
    get: operations['getApiCookies'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download a file
     * @description Returns a binary file with Content-Disposition header for responseType testing.
     */
    get: operations['getApiDownload'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/headers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Test header validation
     * @description Test endpoint for header validation.
     */
    get: operations['getApiHeaders'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/hello': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Hello endpoint
     * @description Returns a greeting message with timestamp and method.
     */
    get: operations['getApiHello'];
    put?: never;
    /**
     * Hello POST endpoint
     * @description Echoes back the received body with a greeting.
     */
    post: operations['postApiHello'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Form data validation test
     * @description Test endpoint for form data validation.
     */
    post: operations['postApiLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/request-demo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Typed internal fetch demo
     * @description Demonstrates server-side typed internal fetch by calling other API routes in-process.
     */
    get: operations['getApiRequestDemo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search with query validation
     * @description Test endpoint for query parameter validation.
     */
    get: operations['getApiSearch'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/text': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Plain text response
     * @description Returns a plain text response for testing responseType: "text".
     */
    get: operations['getApiText'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user by ID
     * @description Returns a single user by their ID.
     */
    get: operations['getApiUsersById'];
    /**
     * Update user by ID
     * @description Updates a user by their ID.
     */
    put: operations['putApiUsersById'];
    post?: never;
    /**
     * Delete user by ID
     * @description Deletes a user by their ID.
     */
    delete: operations['deleteApiUsersById'];
    options?: never;
    head?: never;
    /**
     * Patch user by ID
     * @description Partially updates a user by their ID.
     */
    patch: operations['patchApiUsersById'];
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all users
     * @description Returns a list of all users in the system.
     */
    get: operations['getApiUsers'];
    put?: never;
    /**
     * Create a new user
     * @description Creates a new user in the system.
     */
    post: operations['postApiUsers'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getApiCookies: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        /** @description Session ID cookie */
        session?: string;
        /** @description Theme preference cookie */
        theme?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Cookies received and validated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getApiDownload: {
    parameters: {
      query?: {
        /** @description Filename for the downloaded file */
        filename?: string;
        /** @description Content-Type of the response */
        contentType?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Binary file content */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
    };
  };
  getApiHeaders: {
    parameters: {
      query?: never;
      header?: {
        /** @description Request ID header */
        'x-request-id'?: string;
        /** @description A custom test header */
        'x-custom-header'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Headers received and validated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getApiHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Greeting object */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message?: string;
            timestamp?: string;
            method?: string;
          };
        };
      };
    };
  };
  postApiHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Echo response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
    };
  };
  postApiLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** @description Username (min 3 characters) */
          username: string;
          /** @description Password (min 6 characters) */
          password: string;
          /**
           * Format: email
           * @description Email address
           */
          email: string;
        };
      };
    };
    responses: {
      /** @description Form data received and validated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getApiRequestDemo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aggregated results from internal calls */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
    };
  };
  getApiSearch: {
    parameters: {
      query: {
        /** @description Search query string */
        q: string;
        /** @description Page number (starts from 1) */
        page?: number;
        /** @description Items per page (default 10) */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Search results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description The search query used */
            query: string;
            /** @description Current page number */
            page: number;
            /** @description Items per page */
            limit: number;
            /** @description Sample results */
            results: string;
            /** @description Response timestamp */
            timestamp: string;
          };
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getApiText: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Plain text content */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  getApiUsersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The requested user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  putApiUsersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The updated user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteApiUsersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deletion confirmed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patchApiUsersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The patched user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getApiUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            users: {
              /** @description The unique identifier for the user */
              id: number;
              /** @description The name of the user */
              name: string;
              /** @description The email of the user */
              email: string;
              /** @description The role of the user */
              role: string;
            }[];
            /** @description Total number of users */
            total: number;
          };
        };
      };
    };
  };
  postApiUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description The name of the user */
          name: string;
          /** @description The email of the user */
          email: string;
          /** @description The role of the user */
          role: string;
        };
      };
    };
    responses: {
      /** @description The created user */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description The unique identifier for the user */
            id: number;
            /** @description The name of the user */
            name: string;
            /** @description The email of the user */
            email: string;
            /** @description The role of the user */
            role: string;
          };
        };
      };
    };
  };
}
